export const tableData = [
  {
    first_name: "Hiroko",
    last_name: "Spence",
    email: "sociis.natoque@liberoDonec.edu",
    phone: "(01062) 727578",
    date_of_birth: "Apr 9, 2022",
    sex: "Male",
  },
  {
    first_name: "Merrill",
    last_name: "Jacobson",
    email: "non@Etiam.ca",
    phone: "0988 907 4876",
    date_of_birth: "Aug 19, 2021",
    sex: "Female",
  },
  {
    first_name: "Kalia",
    last_name: "Petty",
    email: "arcu@ligula.ca",
    phone: "0364 797 3614",
    date_of_birth: "May 12, 2022",
    sex: "Female",
  },
  {
    first_name: "Travis",
    last_name: "Pierce",
    email: "libero.Proin.mi@laciniamattis.com",
    phone: "(021) 0797 1242",
    date_of_birth: "Mar 14, 2022",
    sex: "Male",
  },
  {
    first_name: "Noah",
    last_name: "Daniels",
    email: "enim@nullaIntincidunt.co.uk",
    phone: "0959 035 4204",
    date_of_birth: "Aug 21, 2021",
    sex: "Male",
  },
  {
    first_name: "Dale",
    last_name: "Peterson",
    email: "orci.lobortis@eudolor.edu",
    phone: "(0118) 285 9938",
    date_of_birth: "Oct 15, 2020",
    sex: "Male",
  },
  {
    first_name: "Slade",
    last_name: "Nicholson",
    email: "sapien@pellentesqueSed.com",
    phone: "055 2139 5402",
    date_of_birth: "Mar 18, 2022",
    sex: "Male",
  },
  {
    first_name: "Dorian",
    last_name: "Rosales",
    email: "ullamcorper@volutpat.org",
    phone: "0840 340 6578",
    date_of_birth: "Jul 1, 2022",
    sex: "Male",
  },
  {
    first_name: "Whilemina",
    last_name: "Dillon",
    email: "augue@dapibusrutrum.com",
    phone: "056 8252 9974",
    date_of_birth: "Aug 31, 2021",
    sex: "Female",
  },
  {
    first_name: "August",
    last_name: "Wilkerson",
    email: "dui.Fusce.diam@acmattisvelit.ca",
    phone: "0800 1111",
    date_of_birth: "May 4, 2022",
    sex: "Female",
  },
  {
    first_name: "Malachi",
    last_name: "Pearson",
    email: "non.lobortis.quis@egestasligulaNullam.com",
    phone: "0357 089 2509",
    date_of_birth: "Feb 1, 2021",
    sex: "Female",
  },
  {
    first_name: "Grady",
    last_name: "Pruitt",
    email: "congue.elit.sed@litoratorquentper.ca",
    phone: "076 3520 7692",
    date_of_birth: "Nov 2, 2021",
    sex: "Female",
  },
  {
    first_name: "Dillon",
    last_name: "Hurst",
    email: "elementum.purus@eratvolutpatNulla.net",
    phone: "0854 001 9882",
    date_of_birth: "Oct 29, 2021",
    sex: "Female",
  },
  {
    first_name: "Kendall",
    last_name: "Frye",
    email: "vestibulum.Mauris.magna@dictumProin.com",
    phone: "0800 031 7486",
    date_of_birth: "Aug 12, 2021",
    sex: "Female",
  },
  {
    first_name: "Kenyon",
    last_name: "Horne",
    email: "ac@laoreetposuere.org",
    phone: "07624 055861",
    date_of_birth: "Sep 9, 2021",
    sex: "Male",
  },
  {
    first_name: "Illiana",
    last_name: "Vinson",
    email: "Nulla@cursus.co.uk",
    phone: "(0181) 481 6054",
    date_of_birth: "May 10, 2021",
    sex: "Female",
  },
  {
    first_name: "Martena",
    last_name: "Case",
    email: "neque@velpedeblandit.co.uk",
    phone: "07624 932289",
    date_of_birth: "Nov 23, 2020",
    sex: "Female",
  },
  {
    first_name: "Laith",
    last_name: "Delacruz",
    email: "massa.Mauris@sagittis.net",
    phone: "0957 760 9719",
    date_of_birth: "Feb 19, 2021",
    sex: "Male",
  },
  {
    first_name: "Zachary",
    last_name: "Rasmussen",
    email: "vehicula.Pellentesque.tincidunt@posuere.net",
    phone: "(0115) 164 6948",
    date_of_birth: "Nov 24, 2020",
    sex: "Male",
  },
  {
    first_name: "Quynn",
    last_name: "Vargas",
    email: "pulvinar.arcu@SednequeSed.co.uk",
    phone: "0958 982 1167",
    date_of_birth: "Nov 17, 2020",
    sex: "Male",
  },
];
